security:
    password_hashers:
        App\Entity\Cliente:
            algorithm: auto
            cost: 12  # Aumentar la seguridad del hash

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Cliente
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: username
                password_path: password
                success_handler: App\Security\AuthenticationSuccessHandler
                failure_handler: App\Security\AuthenticationFailureHandler

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/products, roles: PUBLIC_ACCESS }
        - { path: ^/api/catalog, roles: PUBLIC_ACCESS }
        - { path: ^/api/categories, roles: PUBLIC_ACCESS }
        - { path: ^/api/upload-image, roles: PUBLIC_ACCESS }
        - { path: ^/api/analytics, roles: PUBLIC_ACCESS }
        - { path: ^/api/orders, roles: PUBLIC_ACCESS }
        - { path: ^/api/checkout, roles: PUBLIC_ACCESS }
        - { path: ^/api$, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
